# frozen_string_literal: true
# <!-- BEGIN AUTOGENERATED ANNOTATIONS -->
# ## Schema Information
#
# Table name: `btc_addresses`
#
# ### Columns
#
# Name              | Type               | Attributes
# ----------------- | ------------------ | ---------------------------
# **`id`**          | `integer`          | `not null, primary key`
# **`user_id`**     | `integer`          |
# **`address`**     | `string`           | `not null`
# **`created_at`**  | `datetime`         | `not null`
# **`updated_at`**  | `datetime`         | `not null`
#
# ### Indexes
#
# * `index_btc_addresses_on_user_id`:
#     * **`user_id`**
#
# ### Foreign Keys
#
# * `fk_rails_776dcc5b39`:
#     * **`user_id => users.id`**
#
# <!-- END AUTOGENERATED ANNOTATIONS -->

require 'rails_helper'

RSpec.describe BtcAddress, type: :model do
  pending "add some examples to (or delete) #{__FILE__}"
end
