# <!-- BEGIN AUTOGENERATED ANNOTATIONS -->
# ## Schema Information
#
# Table name: `btc_txes`
#
# ### Columns
#
# Name                       | Type               | Attributes
# -------------------------- | ------------------ | ---------------------------
# **`id`**                   | `integer`          | `not null, primary key`
# **`btc_address_id`**       | `integer`          |
# **`amount`**               | `decimal(16, 8)`   |
# **`confirmation_status`**  | `integer`          |
# **`coinbase_id`**          | `string`           |
# **`native_amount`**        | `decimal(, )`      |
# **`native_currency`**      | `integer`          |
# **`created_at`**           | `datetime`         | `not null`
# **`updated_at`**           | `datetime`         | `not null`
# **`trade_id`**             | `string`           |
#
# ### Indexes
#
# * `index_btc_txes_on_btc_address_id`:
#     * **`btc_address_id`**
#
# ### Foreign Keys
#
# * `fk_rails_f31e8e88ea`:
#     * **`btc_address_id => btc_addresses.id`**
#
# <!-- END AUTOGENERATED ANNOTATIONS -->

require 'rails_helper'

RSpec.describe BtcTx, type: :model do
  pending "add some examples to (or delete) #{__FILE__}"
end
