host:
  host: app.payload.pk
smtp:
  address: <%= ENV['SMTP_HOST'] %>
  port: <%= ENV['SMTP_PORT'] %>
  user_name: <%= ENV['SMTP_USERNAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
papertrail:
  host: <%= ENV['PAPERTRAIL_HOST'] %>
  port: <%= ENV['PAPERTRAIL_PORT'] %>
