# frozen_string_literal: true
# <!-- BEGIN AUTOGENERATED ANNOTATIONS -->
# ## Schema Information
#
# Table name: `documents`
#
# ### Columns
#
# Name                                   | Type               | Attributes
# -------------------------------------- | ------------------ | ---------------------------
# **`id`**                               | `integer`          | `not null, primary key`
# **`user_id`**                          | `integer`          |
# **`created_at`**                       | `datetime`         | `not null`
# **`updated_at`**                       | `datetime`         | `not null`
# **`cnic_front_file_name`**             | `string`           |
# **`cnic_front_content_type`**          | `string`           |
# **`cnic_front_file_size`**             | `integer`          |
# **`cnic_front_updated_at`**            | `datetime`         |
# **`cnic_back_file_name`**              | `string`           |
# **`cnic_back_content_type`**           | `string`           |
# **`cnic_back_file_size`**              | `integer`          |
# **`cnic_back_updated_at`**             | `datetime`         |
# **`cnic_selfie_file_name`**            | `string`           |
# **`cnic_selfie_content_type`**         | `string`           |
# **`cnic_selfie_file_size`**            | `integer`          |
# **`cnic_selfie_updated_at`**           | `datetime`         |
# **`proof_of_residence_file_name`**     | `string`           |
# **`proof_of_residence_content_type`**  | `string`           |
# **`proof_of_residence_file_size`**     | `integer`          |
# **`proof_of_residence_updated_at`**    | `datetime`         |
#
# ### Indexes
#
# * `index_documents_on_user_id`:
#     * **`user_id`**
#
# ### Foreign Keys
#
# * `fk_rails_2be0318c46`:
#     * **`user_id => users.id`**
#
# <!-- END AUTOGENERATED ANNOTATIONS -->

class Document < ApplicationRecord
  belongs_to :user
  has_attached_file :cnic_front
  validates_attachment_content_type :cnic_front, content_type: %r{\A(image\/(png|jpg|jpeg)|application\/pdf)\z}
  validates_attachment_size :cnic_front, less_than: 5.megabytes

  has_attached_file :cnic_back
  validates_attachment_content_type :cnic_back, content_type: %r{\A(image\/(png|jpg|jpeg)|application\/pdf)\z}
  validates_attachment_size :cnic_back, less_than: 5.megabytes

  has_attached_file :cnic_selfie
  validates_attachment_content_type :cnic_selfie, content_type: %r{\A(image\/(png|jpg|jpeg)|application\/pdf)\z}
  validates_attachment_size :cnic_selfie, less_than: 5.megabytes

  has_attached_file :proof_of_residence
  validates_attachment_content_type :proof_of_residence, content_type: %r{\A(image\/(png|jpg|jpeg)|application\/pdf)\z}
  validates_attachment_size :proof_of_residence, less_than: 5.megabytes
end
