# <!-- BEGIN AUTOGENERATED ANNOTATIONS -->
# ## Schema Information
#
# Table name: `verification_personals`
#
# ### Columns
#
# Name                     | Type               | Attributes
# ------------------------ | ------------------ | ---------------------------
# **`id`**                 | `integer`          | `not null, primary key`
# **`user_id`**            | `integer`          |
# **`name`**               | `string`           |
# **`dob`**                | `date`             |
# **`male`**               | `boolean`          |
# **`email_primary`**      | `string`           |
# **`phone_mobile`**       | `string`           |
# **`phone_secondary`**    | `string`           |
# **`address_current`**    | `string`           |
# **`address_permanent`**  | `string`           |
# **`id_cnic`**            | `string`           |
# **`convicted`**          | `boolean`          |
# **`terrorist`**          | `boolean`          |
# **`created_at`**         | `datetime`         | `not null`
# **`updated_at`**         | `datetime`         | `not null`
#
# ### Indexes
#
# * `index_verification_personals_on_user_id`:
#     * **`user_id`**
#
# ### Foreign Keys
#
# * `fk_rails_6fc5d91c4c`:
#     * **`user_id => users.id`**
#
# <!-- END AUTOGENERATED ANNOTATIONS -->

class VerificationPersonal < ApplicationRecord
  belongs_to :user
end
