# frozen_string_literal: true
# <!-- BEGIN AUTOGENERATED ANNOTATIONS -->
# ## Schema Information
#
# Table name: `withdrawal_options`
#
# ### Columns
#
# Name                  | Type               | Attributes
# --------------------- | ------------------ | ---------------------------
# **`id`**              | `integer`          | `not null, primary key`
# **`user_id`**         | `integer`          | `not null`
# **`option_type`**     | `integer`          | `not null`
# **`bank_name`**       | `string`           |
# **`account_title`**   | `string`           |
# **`account_number`**  | `string`           |
# **`created_at`**      | `datetime`         | `not null`
# **`updated_at`**      | `datetime`         | `not null`
#
# ### Indexes
#
# * `index_withdrawal_options_on_user_id`:
#     * **`user_id`**
#
# ### Foreign Keys
#
# * `fk_rails_4c13725298`:
#     * **`user_id => users.id`**
#
# <!-- END AUTOGENERATED ANNOTATIONS -->

class WithdrawalOption < ApplicationRecord
  belongs_to :user
  enum option_type: %i(bank_account cash_jsbank)
end
